stages:
  data_ingestion:
    cmd: python src/textSummarizer/pipeline/stage_01_data_ingestion.py
    deps:
      - src/textSummarizer/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/samsum_dataset/

  data_validation:
    cmd: python src/textSummarizer/pipeline/stage_02_data_validation.py
    deps:
      - src/textSummarizer/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/textSummarizer/pipeline/stage_03_data_transformation.py
    deps:
      - src/textSummarizer/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/samsum_dataset/

  model_trainer:
    cmd: python src/textSummarizer/pipeline/stage_04_model_trainer.py
    deps:
      - src/textSummarizer/pipeline/stage_04_model_trainer.py
      - config/config.yaml
    outs:
      - artifacts/model_trainer/pegasus-samsum-model
      - artifacts/model_trainer/tokenizer

  model_evaluation:
    cmd: python src/textSummarizer/pipeline/stage_05_model_evaluation.py
    deps:
      - src/textSummarizer/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/model_trainer/tokenizer
      - artifacts/model_trainer/pegasus-samsum-model
      - artifacts/data_transformation/samsum_dataset
    outs:
      - artifacts/model_evaluation/metrics.csv
